name: Build & Deploy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  # Lint
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Install Packages
      - name: Install Packages
        run: bun install --frozen-lockfile

      # Run Lint
      - name: Run Lint
        run: bun run lint

  # Unit Tests
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Install Packages
      - name: Install Packages
        run: bun install --frozen-lockfile

      # Run Unit Tests
      - name: Run Unit Tests
        run: bun run test

      # Upload Coverage
      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

  # Type Check
  type-check:
    name: Run Type Check
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Install Packages
      - name: Install Packages
        run: bun install --frozen-lockfile

      # Run Type Check
      - name: Run Type Check
        run: bun run tsc

  # Build
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, unit-tests, type-check]
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Install Packages
      - name: Install Packages
        run: bun install --frozen-lockfile

      # Build Artifact - Development
      - name: Build Artifact - Development
        if: github.event_name != 'release'
        run: |
          cp .env.development .env
          bun run build

      # Build Artifact - Production
      - name: Build Artifact - Production
        if: github.event_name == 'release'
        run: |
          cp .env.production .env
          bun run build

      # Upload Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  # Deploy
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup GH Pages
      - name: Setup GH Pages
        uses: actions/configure-pages@v5

      # Download Artifact
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      # Upload Artifact
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist"

      # Deploy
      - name: Deploy
        uses: actions/deploy-pages@v4
        id: deployment
